<?php

use Nette\Application\Routers\RouteList,
    Nette\Application\Routers\Route,    
    Nette\Utils\Strings;
use Nette\Diagnostics\Debugger;

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';


$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../log');


// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
	->register();

$webloaderExtension = new \WebLoader\Nette\Extension();
$webloaderExtension->install($configurator);

$gapiExtension = new \Birne\Gapi\Extension();
$gapiExtension->install($configurator);

// Translation setup
$configurator->onCompile[] = function ($configurator, $compiler) {
    $compiler->addExtension('netteTranslator', new NetteTranslator\NetteTranslatorExtension);
};

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section


$container = $configurator->createContainer();

$router = new RouteList;

Route::addStyle('slug');
Route::setStyleProperty('slug', Route::FILTER_OUT, function($url) {
    return Strings::webalize($url);
});

Route::setStyleProperty('slug', Route::FILTER_IN, function($url) {
    return Strings::webalize($url);
});

$router[] = new Route('<catID>[-<slug>][/<lang [a-z]{2}>]', 'Product:products');

$router[] = new Route('koupit/<id>[-<slug>][/<lang [a-z]{2}>]', 'Product:product');
$router[] = new Route('koupit/<id>[/<lang [a-z]{2}>]', 'Product:product');
$router[] = new Route('novinky/<blogid>-<slug>[/<lang [a-z]{2}>]', 'Blog:posts');
$router[] = new Route('novinky/clanek/<postid>[-<slug>][/<lang [a-z]{2}>]', 'Blog:post');

$router[] = new Route('informace/<spostid>-<slug>[/<lang [a-z]{2}>]', 'Blog:staticText');

$router[] = new Route('index.php', 'Homepage:default', Route::ONE_WAY);
$router[] = new Route('<presenter>/<action>[/<id>][/<lang [a-z]{2}>]', 'Homepage:default');

$container->addService('router', $router);




return $container;
