<?php

use Nette\Application\Routers\RouteList,
    Nette\Application\Routers\Route;

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';


$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
	->register();

//Bootstrap forms
Kdyby\BootstrapFormRenderer\DI\RendererExtension::register($configurator);

//Replicator
Kdyby\Replicator\Container::register();

// Translation setup
$configurator->onCompile[] = function ($configurator, $compiler) {
    $compiler->addExtension('netteTranslator', new NetteTranslator\NetteTranslatorExtension);
};

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section


$container = $configurator->createContainer();

$router = new RouteList;
$router[] = new Route('produkt/<id>', 'Product:product');
$router[] = new Route('novinky/<id>', 'Blog:posts');
$router[] = new Route('novinky/clanek/<postid>', 'Blog:post');
$router[] = new Route('kosik/', 'Order:cart');
$router[] = new Route('informace/<postid>', 'Blog:staticText');
$router[] = new Route('<presenter>/<action>[/<id>]', 'Homepage:default');

$container->addService('router', $router);

       

return $container;
